services:
  - name: epg-server
    type: web
    env: docker
    httpPort: 10000
    dockerfilePath: ./backend/epg-generator/Dockerfile
    dockerContext: .
    dockerCommand: "php -S 0.0.0.0:10000 -t /var/cache/render/xmltv"
    cache:
      name: epg-cache
      path: /var/cache/render

  - name: epg-generator
    type: cron
    env: docker
    schedule: "0 * * * *"
    dockerfilePath: ./backend/epg-generator/Dockerfile
    dockerContext: .
    dockerCommand: "mkdir -p /var/cache/render/xmltv && php manager.php export"
    cache:
      name: epg-cache
      path: /var/cache/render

caches:
  - name: epg-cache

