services:
  # Web Service to serve the generated EPG file
  - type: web
    name: epg-server
    runtime: docker
    dockerfilePath: ./backend/epg-generator/Dockerfile
    dockerContext: ./backend/epg-generator
    # The build command copies our custom config files into the container
    buildCommand: "cp epg-config/* backend/epg-generator/config/"
    startCommand: "php -S 0.0.0.0:10000 -t /var/data/xmltv"
    httpPort: 10000
    disks:
      - name: epg-data
        mountPath: /var/data

  # Cron Job to generate the EPG file
  - type: cron
    name: epg-generator
    schedule: "0 * * * *" # Every hour
    dockerfilePath: ./backend/epg-generator/Dockerfile
    dockerContext: ./backend/epg-generator
    # The build command copies our custom config files into the container
    buildCommand: "cp epg-config/* backend/epg-generator/config/"
    command: "php manager.php export"
    disks:
      - name: epg-data
        mountPath: /var/data

disks:
  - name: epg-data
    sizeGB: 1

