services:
  # Web Service to serve the generated EPG file
  - type: web
    name: epg-server
    runtime: docker
    dockerfilePath: ./backend/epg-generator/Dockerfile
    dockerContext: .
    dockerCommand: "php -S 0.0.0.0:10000 -t /var/cache/render/xmltv"
    httpPort: 10000
    previews: true # Enable cache

  # Cron Job to generate the EPG file
  - type: cron
    name: epg-generator
    schedule: "0 * * * *" # Every hour
    dockerfilePath: ./backend/epg-generator/Dockerfile
    dockerContext: .
    dockerCommand: "mkdir -p /var/cache/render/xmltv && php manager.php export"
    previews: true # Enable cache

